[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
hw = "6UtsrVdAgsoydvmMo1kUXMDfa9aCNn7uSkG9GTaNazDv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/hongrunzhou/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
